// <auto-generated />
using ControleChamadosRedeSuporte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleChamadosRedeSuporte.Migrations
{
    [DbContext(typeof(CCRSContext))]
    partial class CCRSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleChamadosRedeSuporte.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GraduacaoId");

                    b.Property<string>("Name");

                    b.Property<int>("Rg");

                    b.Property<int>("Tipo");

                    b.Property<int>("UnidadeId");

                    b.HasKey("Id");

                    b.HasIndex("GraduacaoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ControleChamadosRedeSuporte.Models.Graduacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Grad");

                    b.HasKey("Id");

                    b.ToTable("Graduacao");
                });

            modelBuilder.Entity("ControleChamadosRedeSuporte.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("ControleChamadosRedeSuporte.Models.Funcionario", b =>
                {
                    b.HasOne("ControleChamadosRedeSuporte.Models.Graduacao", "Graduacao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("GraduacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ControleChamadosRedeSuporte.Models.Unidade", "Unidade")
                        .WithMany("Funcionarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
